name: Realizar build e deploy do webapp

on:
  push:
    branches:
      - develop
      - main
      - 'feature/**'

jobs:
  backup-versao-atual:
    runs-on: ubuntu-latest
    steps:
      - name: Executar backup da última versão do front
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            CURRENT_DATE_FRONT=$(date +"%Y%m%d%H%M%S")
            sudo mkdir -p /opt/backup/frontend/${CURRENT_DATE}

  # build-and-deploy:
  #   runs-on: ubuntu-latest
  #   needs: backup-versao-atual
  #   steps:
  #   - name: Baixar repositório na branch atual
  #     uses: actions/checkout@v2

  #   - name: Configurar NodeJS na versão 18
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: '18'

  #   - name: Instalar Dependências
  #     run: npm install

  #   - name: Construir webapp React final
  #     run: npm run build
    
  #   - name: Configurar chave SSH para acessar VM
  #     uses: webfactory/ssh-agent@v0.5.3
  #     with:
  #       ssh-private-key: ${{ secrets.VM_SSH_KEY }}

  #   - name: Enviar arquivos do build para a 
  #     run: rsync -avz --delete ./build/ ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:/opt/apps/frontend/